[package]
name = "xswezan/component"
description = "Bind component to instances using CollectionService"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["lib", "lib/**/*.luau", "wally.toml"]

[dependencies]
Janitor = "howmanysmall/janitor@1.18.3"