[package]
name = "xswezan/modulename"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.18.3"
Promise = "lukadev-0/typed-promise@4.0.2"